config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/q(/:query)", to: "search#index", as: "search"
  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/movies_controller.rb
require 'omdb'
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
    omdb = Omdb.new
    @resp = omdb.find_by_id(@movie.imdb_id)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :poster, :user_id, :imdb_id)
    end
end

app/controllers/search_controller.rb
require "omdb"
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    omdb = Omdb.new
    @query = params[:query]
    unless @query.nil?
    @resp = omdb.find_by_title(@query)
    end
    @new_movie = Movie.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper

  def reject_keys(keys, rejected_keys)
    keys.reject { |k| rejected_keys.include? k.downcase.to_sym }
  end

  def include_keys(keys, included_keys)
    keys.reject { |k| !included_keys.include? k.downcase.to_sym }
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.erb
 <div class="hero min-h-screen bg-base-200">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold">Welcome to the Movies!</h1>
      <p class="py-6">Create your user using the sign up link</p>
      <%=link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
 <% flash.each do |key, value| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
      </div>
    </div>
  </div>
<% end -%>

app/views/layouts/_menu.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li>
          <a>Parent</a>
          <ul class="p-2">
            <li><a>Submenu 1</a></li>
            <li><a>Submenu 2</a></li>
          </ul>
        </li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
    <a class="btn btn-ghost text-xl" href="/">The Movies</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <% if current_user %>
      <li><%= link_to "Search", search_path %></li>
      <li><%= link_to "My movies", movies_path %></li>
      <li>
        <details>
          <summary><%= current_user.email %></summary>
          <ul class="p-2">
            <li><%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </details>
      </li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title>Themovies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render partial: "layouts/menu" %>
    <%= render partial: "layouts/flash" %>
    <div class="container mx-auto prose">
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :poster, style: "display: block" %>
    <%= form.text_field :poster %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :imdb_id, style: "display: block" %>
    <%= form.text_field :imdb_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_kv.html.erb
<div><strong><%= kv %></strong>: <%= movie[kv] %></div>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
  <img src="<%= movie.poster %>"/>
  </p>

</div>

app/views/movies/_omdb_movie.html.erb
<div class="flex flex-row gap-4 w-2/3 mx-auto">
  <div class="flex-none">
    <img class="m-0" src="<%= movie[:Poster]%>" alt="Poster" />
  </div>
  <div>
    <%= render collection: include_keys(movie.keys, [:title, :plot, :actors]), partial: "movies/kv", locals: { movie: movie } %>
    <%= form_with(model: new_movie) do |f| %>
      <%= f.hidden_field :title, value: movie[:Title] %>
      <%= f.hidden_field :poster, value: movie[:Poster] %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :imdb_id, value: movie[:imdbID] %>

      <div>
        <%= f.submit "Add movie to collection", class: "btn" %>
      </div>
    <% end %>
  </div>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<%= render @movie %>

<%= render collection: reject_keys(@resp.keys, [:poster, :ratings]), partial: "movies/kv", locals: { movie: @resp } %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/search/index.html.erb
<h1>Search</h1>

<%= form_with url: "/q", method: :get do |form| %>
 <label class="input input-bordered flex items-center gap-2">
   <input type="text" class="grow" placeholder="Search" name="query" value="<%= @query %>"/>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70"><path fill-rule="evenodd" d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z" clip-rule="evenodd" /></svg>
</label>
  <%= form.submit "Search", class: "btn my-5" %>
<% end %>

<%= render partial: "movies/omdb_movie", locals: { movie: @resp, new_movie: Movie.new } unless @resp.nil? %>